### ISSUE TITLE
Todo for Beta release

### ISSUE THREAD

**Issue by ToddThomson** [ToddThomson/Mila#1]
Work in progress...

* Mila API
  - [ ] Document public API

* C++ 20 Modules
  - [x] Rename source filenames for VS2022 scanning and searching for IFCs 

* General 
  - [ ] Credit to contributors

**Comment by ToddThomson** [comment]
Mila has progressed considerably since this early tracking issue. I am closing as it is not longer relevant.
